#!/bin/sh

set -e

URL="https://github.com/mattrighetti/envelope/blob/master/CHANGELOG.md"
TAG="$(git tag --points-at HEAD)"
REF="${TAG//.}---$(git show -s --format=%cd --date=short)"
CHANGELOG_REF="${URL}#${REF}"
NOTES="[CHANGELOG](${CHANGELOG_REF})"

gh release create $1 --notes="${NOTES}"
